version: 2.0
jobs:
 build:
   docker:
    - image: armutcom/aspnet-core:2.2.3-xenial
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
     - run:
         name: Run App
         command:
           dotnet run